### ISSUE TITLE
publish to jitpack

### ISSUE THREAD

**Issue by prempalsingh** [Cutta/GifView#2]
You should make a release and publish this to jitpack.io. It's really easy and convenient.

**Comment by digitalbuddha** [comment]
MavenCental or Jcenter not jitpack please

**Comment by rocboronat** [comment]
@digitalbuddha +1

**Comment by anvesh523** [comment]
+1

**Comment by AndroidDeveloperLB** [comment]
+1
And, I don't care if Jitpack or not. For me it's the same.

**Comment by rpaschapur** [comment]
@digitalbuddha +1

**Comment by bradmartin** [comment]
+1

**Comment by Cutta** [comment]
Published 👍
