### ISSUE TITLE
Build project show this error?Android Studio2.3

### ISSUE THREAD

**Issue by meicuihui** [Cutta/GifView#20]
Error:(65, 13) Failed to resolve: com.github.Cutta:GifView:1.1
Show in File
open.dependency.in.project.structure
Show in Project Structure dialog
![0iy4 mz l kl d bsus1](https://user-images.githubusercontent.com/18278015/34399716-13a86918-ebc5-11e7-9d30-61c5242cc02b.png)

**Comment by Cutta** [comment]
Hi @SbyXlmm  
I tried it on sample project and can download and use the library. I think you didn't add "jcenter" to your project-build file (not `build.gradle (Module:app)`. You can add like this.
```
allprojects {
    repositories {
        jcenter()
    }
}
```

**Comment by saraXX** [comment]
not working :(

> Hi @SbyXlmm
> I tried it on sample project and can download and use the library. I think you didn't add "jcenter" to your project-build file (not `build.gradle (Module:app)`. You can add like this.
> 
> ```
> allprojects {
>     repositories {
>         jcenter()
>     }
> }
> ```

**Comment by ankitk93** [comment]
Hey is this issue fixed ? @meicuihui  @saraXX @Cutta

**Comment by Cutta** [comment]
Hi @saraXX and @ankitk93 
 sorry for my late reply. I updated the lib. Now it can work with targetSdk 28.
Now you can find it with implementation 'com.github.Cutta:GifView:1.4'
