### ISSUE TITLE
Issue in gradle build

### ISSUE THREAD

**Issue by rakeshparveen5** [Cutta/GifView#24]
Could not find GifView.aar (com.github.Cutta:GifView:1.1).
Searched in the following locations:
    https://jitpack.io/com/github/Cutta/GifView/1.1/GifView-1.1.aar

**Comment by sudhirkhanger** [comment]
@rakeshparveen5 have you happen to find a solution for the issue?

**Comment by ankitk93** [comment]
@rakeshparveen5  @sudhirkhanger  did you guys find the issue ?

**Comment by rakeshparveen5** [comment]
I removed this module and now using Glide for loading Gif images

**Comment by ankitk93** [comment]
yeah, this library sucks seems to me.

**Comment by ankitk93** [comment]
@Cutta you should really consider looking after this issue.

**Comment by sudhirkhanger** [comment]
@ankitk93 ended up using https://github.com/koral--/android-gif-drawable

**Comment by Cutta** [comment]
Hi @rakeshparveen5 , @sudhirkhanger and @ankitk93 
Sorry for my late reply. I updated the lib. Now it can work with targetSdk 28. 
Now you can find it with  `implementation 'com.github.Cutta:GifView:1.4'`
Please forgive me for late reply 🙏
