### ISSUE TITLE
it is not working and not syncing with gradle

### ISSUE THREAD

**Issue by jagadish906** [Cutta/GifView#26]
Could not find GifView.aar (com.github.Cutta:GifView:1.1).
Searched in the following locations:
https://jitpack.io/com/github/Cutta/GifView/1.1/GifView-1.1.aar

**Comment by Cutta** [comment]
Hi @jagadish906 sorry for my late reply. I updated the lib. Now it can work with targetSdk 28. 
Now you can find it with  implementation 'com.github.Cutta:GifView:1.4'
