### ISSUE TITLE
I think you should point out that you project is fork from this project “ sbakhtiarov/gif-movie-view”

### ISSUE THREAD

**Issue by wonTonx** [Cutta/GifView#6]
your GifView.java is exactly the same clss from the sbakhtiarov's project
here are the link:https://github.com/sbakhtiarov/gif-movie-view

**Comment by RanceAttack** [comment]
omg

**Comment by adnbsr** [comment]
At least you can change comments on methods :). Anyway, do not forget to report him for infringement.

**Comment by Cutta** [comment]
I will change and of course I improve it. I didn't know this library. I show reference this library on README
